<?php $this->layout('layout/layout', ["title" => "Surf content"]); ?>

<div class="welcome">
	<h1>BIENVENUE SUR SURF CONTENT</h1>
	<p>Choisissez votre spot</p>
</div>

<div class="preferSpot">
	<div class="row">
		<div class="col-8">
			<div class="card favSpot">
				<img src="pictures/spot_surf_1.jpg" class="card-img-top">
				<div class="card-img-overlay">
					<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				</div>
			</div>
		</div>
		<div class="col-4">
			<div class="card favSpot">
				<img src="pictures/spot_surf_1.jpg" class="card-img-top">
				<div class="card-img-overlay">
					<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				</div>
			</div>
			<div class="card favSpot">
				<img src="pictures/spot_surf_1.jpg" class="card-img-top">
				<div class="card-img-overlay">
					<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				</div>
			</div>
		</div>
	</div>
</div>