<form id="regForm" action="">

<?php $this->layout('layout/layout', ["title" => "Saisie"]); ?>

<h1>Enregistrer une session </h1>

<!-- One "tab" for each step in the form: -->
<div class="tab">Spot :
  <div class="form-group">
    <select class="form-control" name="spot" id="spot">
      <option value="">-- Choisissez une option --</option>
      <option value="1">La plage de Contis - St-Julien-en-Born </option>
      <option value="2">Biscarrosse-Plage - Biscarrosse </option>
      <option value="3">Plage centrale - Vieux-Boucau-Les-Bains </option>
      <option value="4">Plage du métro - Tarnos </option>
    </select>
  </div>
</div>

<div class="tab">Date :
 <p><input type="date" class="form-control" name="dateSession" id="dateSession" required></p>
 Heure de début :
 <p><input type="time" class="form-control" name="heureDebut" id="heureDebut" required></p>
 Heure de fin :
 <p><input type="time" class="form-control" name="heureFin" id="heureFin" required></p>
</div>

<div class="tab">
  <div class="controls">
    Activité pratiquée :
    <select class="form-control custom-select" name="activite" id="activite">
      <option value="">-- Choisissez une option --</option>
      <option value="1">Surf </option>
      <option value="2">Kite surf </option>
      <option value="3">Baignade </option>
      <option value="4">Plongée </option>
    </select>
  </div>
</div>

<div class="tab">Fréquentation :
  <div class="form-group">
    <select class="form-control" name="nbBaigneur" id="nbBaigneur">
      <option value="">Nombre de baigneur :</option>
      <option value="1">Faible</option>
      <option value="2">Moyen</option>
      <option value="3">Important</option>
    </select>
  </div>
  <div class="form-group">
    <select class="form-control" name="nbPratiquant" id="nbPratiquant">
      <option value="">Nombre de pratiquant :</option>
      <option value="1">Faible</option>
      <option value="2">Moyen</option>
      <option value="3">Important</option>
    </select>
  </div>
  <div class="form-group">
    <select class="form-control" name="freqEspaceMaritime" id="freqEspaceMaritime">
      <option value="">Fréquentation de l'espace maritime :</option>
      <option value="1">Faible</option>
      <option value="2">Moyen</option>
      <option value="3">Important</option>
    </select>
  </div>
</div>

<div class="tab">Produit utilisé dans la journée :
  <br/>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Crême solaire</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox2" value="option2">
    <label class="form-check-label" for="inlinecheckbox2">Parfum / Déodorant </label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Crème hydratante</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Maquillage</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Essence</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Cigarette</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Engrais / Presticides</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Peinture</label>
  </div>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="inlinecheckboxOptions" id="inlinecheckbox1" value="option1">
    <label class="form-check-label" for="inlinecheckbox1">Autre</label>
  </div>
</div>

<div class="tab">Votre ressenti sur cette session :
  <div class="ressenti">
    <div class="form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
      <label class="form-check-label">1</label>
    </div>
    <div class="form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
      <label class="form-check-label">2</label>
    </div>
    <div class="form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option3">
      <label class="form-check-label">3</label>
    </div>
    <div class="form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option4">
      <label class="form-check-label">4</label>
    </div>
    <div class="form-check form-check-inline">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option5">
      <label class="form-check-label">5</label>
    </div>
  </div>
</div>


<div style="overflow:auto;">
 <div style="float:right;">
   <button type="button" class="login-button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
   <button type="button" class="login-button" id="nextBtn" onclick="nextPrev(1)">Next</button>
 </div>
</div>

<!-- Circles which indicates the steps of the form: -->
<div style="text-align:center;margin-top:40px;">
 <span class="step"></span>
 <span class="step"></span>
 <span class="step"></span>
 <span class="step"></span>
 <span class="step"></span>
 <span class="step"></span>
</div>

</form>
