<?php $this->layout('layout/layout', ["title" => "Connexion"]); ?>

  <div class="login">
    <form  method="post" action="">
      <h2>Connexion</h2>
      <input type="text" class="form-control" name="login" id="login" required>
      <h2>Mot de passe</h2>
      <input type="password" class="form-control" name="password" id="password" required>
      <button type="submit" class="login-button">Connexion</button>
    </form>
  </div>
