<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/png" href="../img/logo_moi_content.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/styles.css">
    
	<link rel="icon" type="image/png" href="pictures/logo_moi_content.png">
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title><?= $title ?></title>
</head>

<?= (!empty($onload)) ? "<body onload=\" $onload \" >": "<body onload=\"\" >";?>
    <header>
        <nav class="navbar navbar-expand-lg text-uppercase fixed-top" id="mainNav">
            <div class="containerNav">
                <img class="logoNavBar" src="img/logo_moi_content.png"></img>
                <span class="navbar-brand">Surfer Content</span>
                <ul class="buttonCollapse">
                    <li class="nav-item"><a class="nav-link rounded" href="#">Categorie 1</a></li>
                    <li class="nav-item"><a class="nav-link rounded" href="#">Categorie 2</a></li>
                    <li class="nav-item"><a class="nav-link rounded" href="#">Categorie 3</a></li>
                    <li class="nav-item iconUserBar"><i class="fas fa-user-circle iconUser"></i></li>
                </ul>
            </div>
            </div>
        </nav>
    </header>
    <section class="content">
        <?= require("./templates/views/$body.phtml"); ?>
    </section>
    <footer>
        <div class="copyright py-4 footer">
            <img class="logoFooter" src="img/logo_moi_content.png"></img>
            <span class="navbar-brand js-scroll-trigger">Surfer Content</span>
            <div><small>Copyright © Surf content by Moi Content 2020</small></div>
        </div>
    </footer>

</html>